import Navbar from "./Component/Navbar";
import { GlobalContextProvider } from "./Context/GlobalContext";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Synapsis",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContextProvider>
          {" "}
          <Navbar />
          {children}
        </GlobalContextProvider>
      </body>
    </html>
  );
}
